# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.4.0-browsers-legacy

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            # - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-{{ checksum "yarn.lock" }} # MAYBE ?? since I use/rely on Yarn now.
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # - run: npm install
      # - run: npm ci
      - run: yarn install # since 2021
      # - run: npm run prodBuild
      - run: yarn build # since 2021

      - save_cache:
          paths:
            - node_modules
          # key: v1-dependencies-{{ checksum "package.json" }}
          key: v1-dependencies-{{ checksum "yarn.lock" }} # MAYBE ?? since I use/rely on Yarn now.

      # run tests!
      # - run: npm test
      - run: yarn test # since 2021

      # Storybook Static build
      # - run: npm run build-storybook
      # - run: yarn build-storybook # since 2021 - NOT YET WORKING - commenting temp.
      #
      # in future - in 2021 still future :)
      #- run: npm version patch
      #- run: npm publish
